### ISSUE TITLE
Slow down with Vimeo

### ISSUE THREAD

**Issue by fvlasie** [breezefront/module-breeze-mageworx-advancedproductoptions#3]
Hello,

When using a Vimeo video background in PageBuilder, [PageSpeed Insights](https://pagespeed.web.dev/) complains about redudant Javascript and suggests lazy loading.

<img width="987" alt="Screenshot 2023-07-05 at 1 27 57 PM" src="https://github.com/breezefront/module-breeze-mageworx-advancedproductoptions/assets/33334298/98355803-f42f-4f0f-93b5-4e9d40339e35">

**Comment by vovayatsyuk** [comment]
1. This is a mageworx integration repo.
2. I recommend using a direct link to mp4 video file.

**Comment by fvlasie** [comment]
Sorry! I posted this in the wrong repo!
