### ISSUE TITLE
Compatibility with version 2.36.4

### ISSUE THREAD

**Issue by fvlasie** [breezefront/module-breeze-mageworx-advancedproductoptions#4]
Hello!

Unfortunately Mageworx Advanced Product Options is broken again with version 2.36.4. 
I have requested again that Mageworx include support for the Breeze themes but no luck so far.

The price is not updating properly when options are selected: https://easternchristiansupply.biz/index.php/cse/st-catherine-the-great-martyr-full-scene.html

Thank you!

**Comment by vovayatsyuk** [comment]
You have to re-apply these patches after each update: https://github.com/breezefront/module-breeze-mageworx-advancedproductoptions#required-patches

**Comment by fvlasie** [comment]
I applied the changes but it did not work right away...now it is working. It must have been a stubborn caching issue.

Thank you Vova!
