### ISSUE TITLE
Image replacer not working using the latest version

### ISSUE THREAD

**Issue by IbrahimS2** [breezefront/module-breeze-mageworx-advancedproductoptions#6]
![image](https://github.com/breezefront/module-breeze-mageworx-advancedproductoptions/assets/19901858/b5d2c5b7-89e2-4e63-a1d3-fb30f2f982b7)

**Comment by vovayatsyuk** [comment]
I hope this commit will fix the issue: https://github.com/breezefront/module-breeze-mageworx-advancedproductoptions/commit/ef8131b4919557ba83e016812cfb3810abe252ea

**Comment by IbrahimS2** [comment]
@vovayatsyuk Not working still, the add to cart does not trigger the validation in case of mandatory options and it keeps reloading the pages?
