### ISSUE TITLE
Dependency options aren't working

### ISSUE THREAD

**Issue by rommmka** [breezefront/module-breeze-mageworx-advancedproductoptions#7]
**Breeze version:**
https://kiltattire.com/county-offaly-irish-ancient-tartan-kilt.html
![image](https://github.com/user-attachments/assets/cb436997-4e0c-4321-8ab5-40e2e13181e9)

**Breeze-off version:**
https://kiltattire.com/county-offaly-irish-ancient-tartan-kilt.html?breeze=0
![image](https://github.com/user-attachments/assets/3708f6dc-97af-4156-9886-4df050c8f06f)

**Comment by vovayatsyuk** [comment]
How can I reproduce the issue? If I open https://kiltattire.com/county-offaly-irish-ancient-tartan-kilt.html?breeze=0, I see all colors in both breeze and non-breeze versions.

**Comment by vovayatsyuk** [comment]
It's broken because of `Uncaught TypeError: Cannot read properties of undefined (reading 'initStripeExpress')` error. Please install  https://github.com/breezefront/module-breeze-stripe-payments to fix stripe error.
